/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.avatica.remote.looker;


import java.util.Properties;

public class LookerTestCommon {

  private LookerTestCommon() {
  }

  private static final String BASE_URL = "https://localhost:19999";
  private static final String CLIENT_ID = "f6qG2zPw464yStBrJwrT";
  private static final String CLIENT_SECRET = "KQTpGMPp5mWRQy2Mgrs4SdQT";
  private static final String URL = "jdbc:looker:url=" + BASE_URL;

  private static final Properties BASE_PROPS = new Properties();

  static final String USER_AGENT = ";userAgent=FooBarInc";

  static {
    BASE_PROPS.put("user", CLIENT_ID);
    BASE_PROPS.put("password", CLIENT_SECRET);
    BASE_PROPS.put("verifySSL", "false");
  }

  public static String getUrl() {
    return URL;
  }

  public static Properties getBaseProps() {
    return BASE_PROPS;
  }

  /**
   * Calcite signature for the query:
   *
   * SELECT `users.created_date`, `users.created_year`, `users.created_time`, `users.name`,
   * `users.age`, `users.is45or30`, SUM(`users.age`), AGGREGATE(`users.average_age`) FROM
   * example.users GROUP BY 1, 2, 3, 4, 5, 6
   */
  public static String stubbedSignature = "{\"columns\":[{\"ordinal\":0,\"autoIncrement\":false,"
      + "\"caseSensitive\":true,\"searchable\":false,\"currency\":false,\"nullable\":1,"
      + "\"signed\":true,\"displaySize\":0,\"label\":\"users.created_date\","
      + "\"columnName\":\"users.created_date\",\"schemaName\":\"example\",\"precision\":0,"
      + "\"scale\":0,\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\","
      + "\"id\":91,\"name\":\"DATE\",\"rep\":\"INTEGER\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Date\"},{\"ordinal\":1,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":10,\"label\":\"users.created_year\","
      + "\"columnName\":\"users.created_year\",\"schemaName\":\"example\",\"precision\":10,"
      + "\"scale\":0,\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\","
      + "\"id\":4,\"name\":\"INTEGER\",\"rep\":\"INTEGER\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.lang.Integer\"},{\"ordinal\":2,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":0,\"label\":\"users.created_time\","
      + "\"columnName\":\"users.created_time\",\"schemaName\":\"example\",\"precision\":0,"
      + "\"scale\":0,\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\","
      + "\"id\":93,\"name\":\"TIMESTAMP\",\"rep\":\"LONG\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Timestamp\"},{\"ordinal\":3,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":-1,\"label\":\"users.name\","
      + "\"columnName\":\"users.name\",\"schemaName\":\"example\",\"precision\":0,\"scale\":0,"
      + "\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\",\"id\":12,"
      + "\"name\":\"VARCHAR\",\"rep\":\"STRING\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.lang.String\"},{\"ordinal\":4,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":15,\"label\":\"users.age\","
      + "\"columnName\":\"users.age\",\"schemaName\":\"example\",\"precision\":15,\"scale\":0,"
      + "\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\",\"id\":8,"
      + "\"name\":\"DOUBLE\",\"rep\":\"DOUBLE\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.lang.Double\"},{\"ordinal\":5,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":1,\"label\":\"users.is45or30\","
      + "\"columnName\":\"users.is45or30\",\"schemaName\":\"example\",\"precision\":1,"
      + "\"scale\":0,\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\","
      + "\"id\":16,\"name\":\"BOOLEAN\",\"rep\":\"BOOLEAN\"},\"readOnly\":true,"
      + "\"writable\":false,\"definitelyWritable\":false,\"columnClassName\":\"java.lang"
      + ".Boolean\"},{\"ordinal\":6,\"autoIncrement\":false,\"caseSensitive\":true,"
      + "\"searchable\":false,\"currency\":false,\"nullable\":1,\"signed\":true,"
      + "\"displaySize\":15,\"label\":\"EXPR$6\",\"columnName\":\"EXPR$6\",\"schemaName\":null,"
      + "\"precision\":15,\"scale\":0,\"tableName\":null,\"catalogName\":null,"
      + "\"type\":{\"type\":\"scalar\",\"id\":8,\"name\":\"DOUBLE\",\"rep\":\"DOUBLE\"},"
      + "\"readOnly\":true,\"writable\":false,\"definitelyWritable\":false,"
      + "\"columnClassName\":\"java.lang.Double\"},{\"ordinal\":7,\"autoIncrement\":false,"
      + "\"caseSensitive\":true,\"searchable\":false,\"currency\":false,\"nullable\":0,"
      + "\"signed\":true,\"displaySize\":-1,\"label\":\"EXPR$7\",\"columnName\":\"EXPR$7\","
      + "\"schemaName\":null,\"precision\":0,\"scale\":0,\"tableName\":null,\"catalogName\":null,"
      + "\"type\":{\"type\":\"scalar\",\"id\":8,\"name\":\"MEASURE<DOUBLE>\",\"rep\":\"OBJECT\"},"
      + "\"readOnly\":true,\"writable\":false,\"definitelyWritable\":false,"
      + "\"columnClassName\":\"java.lang.Double\"}],\"sql\":\"select `users.created_date`,`users"
      + ".created_year`, `users.created_time`, `users.name`, `users.age`, `users.is45or30`, SUM"
      + "(`users.age`), AGGREGATE(`users.average_age`) from example.users GROUP BY 1, 2, 3, 4, 5,"
      + " 6\",\"parameters\":[],\"cursorFactory\":{\"style\":\"ARRAY\",\"clazz\":null,"
      + "\"fieldNames\":null},\"statementType\":\"SELECT\"}";

  /**
   * This is a real response from Looker for the following query in `json_bi` format:
   *
   * SELECT `users.created_date`, `users.created_year`, `users.created_time`, `users.name`,
   * `users.age`, `users.is45or30`, SUM(`users.age`), AGGREGATE(`users.average_age`) FROM
   * example.users GROUP BY 1, 2, 3, 4, 5, 6
   */
  public static String stubbedJsonResults = "{\"metadata\":{\"columns_truncated\":false,"
      + "\"has_totals\":false,\"has_subtotals\":false,\"fields\":{\"dimensions\":[{\"sql\":\"{% "
      + "if _dialect._name contains 'druid' %} TIME_PARSE(${TABLE}.created_at, 'yyyy-MM-dd "
      + "HH:mm:ss') {% else %} ${TABLE}.created_at {% endif %}\\n      \",\"view\":\"users\","
      + "\"dimension_group\":\"users.created\",\"field_group_label\":\"Created Date\","
      + "\"category\":\"dimension\",\"name\":\"users.created_date\",\"type\":\"date_date\","
      + "\"view_label\":\"Users\",\"label\":\"Users Created Date\","
      + "\"field_group_variant\":\"Date\",\"hidden\":false,\"description\":null},{\"sql\":\"{% if"
      + " _dialect._name contains 'druid' %} TIME_PARSE(${TABLE}.created_at, 'yyyy-MM-dd "
      + "HH:mm:ss') {% else %} ${TABLE}.created_at {% endif %}\\n      \",\"view\":\"users\","
      + "\"dimension_group\":\"users.created\",\"field_group_label\":\"Created Date\","
      + "\"category\":\"dimension\",\"name\":\"users.created_year\",\"type\":\"date_year\","
      + "\"view_label\":\"Users\",\"label\":\"Users Created Year\","
      + "\"field_group_variant\":\"Year\",\"hidden\":false,\"description\":null},{\"sql\":\"{% if"
      + " _dialect._name contains 'druid' %} TIME_PARSE(${TABLE}.created_at, 'yyyy-MM-dd "
      + "HH:mm:ss') {% else %} ${TABLE}.created_at {% endif %}\\n      \",\"view\":\"users\","
      + "\"dimension_group\":\"users.created\",\"field_group_label\":\"Created Date\","
      + "\"category\":\"dimension\",\"name\":\"users.created_time\",\"type\":\"date_time\","
      + "\"view_label\":\"Users\",\"label\":\"Users Created Time\","
      + "\"field_group_variant\":\"Time\",\"hidden\":false,\"description\":null},{\"sql\":\"users"
      + ".name\",\"view\":\"users\",\"dimension_group\":null,\"field_group_label\":null,"
      + "\"category\":\"dimension\",\"name\":\"users.name\",\"type\":\"string\","
      + "\"view_label\":\"Users\",\"label\":\"Users Name\",\"field_group_variant\":\"Name\","
      + "\"hidden\":false,\"description\":null},{\"sql\":\"users.age\",\"view\":\"users\","
      + "\"dimension_group\":null,\"field_group_label\":null,\"category\":\"dimension\","
      + "\"name\":\"users.age\",\"type\":\"number\",\"view_label\":\"Users\",\"label\":\"Users "
      + "Age\",\"field_group_variant\":\"Age\",\"hidden\":false,\"description\":null},"
      + "{\"sql\":\"${age} = 45 OR ${age} = 30 \",\"view\":\"users\",\"dimension_group\":null,"
      + "\"field_group_label\":null,\"category\":\"dimension\",\"name\":\"users.is45or30\","
      + "\"type\":\"yesno\",\"view_label\":\"Users\",\"label\":\"Users Is45or30 (Yes / No)\","
      + "\"field_group_variant\":\"Is45or30 (Yes / No)\",\"hidden\":false,\"description\":null}],"
      + "\"measures\":[{\"sql\":null,\"view\":\"users\",\"dimension_group\":null,"
      + "\"field_group_label\":null,\"category\":\"measure\",\"name\":\"EXPR__6\","
      + "\"type\":\"sum\",\"view_label\":null,\"label\":\"Users EXPR 6\","
      + "\"field_group_variant\":\"EXPR 6\",\"hidden\":false,\"description\":null},"
      + "{\"sql\":\"${age} \",\"view\":\"users\",\"dimension_group\":null,"
      + "\"field_group_label\":null,\"category\":\"measure\",\"name\":\"users.average_age\","
      + "\"type\":\"average\",\"view_label\":\"Users\",\"label\":\"Users Average Age\","
      + "\"field_group_variant\":\"Average Age\",\"hidden\":false,\"description\":null}],"
      + "\"pivots\":[]},\"pivots\":[],\"filters\":{},"
      + "\"bigquery_metadata\":{\"total_bytes_processed\":0,\"backend_cache_hit\":true}},"
      + "\"rows\":[{\"users.created_date\":{\"value\":15313},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1323114410000},"
      + "\"users.name\":{\"value\":\"Reinoehl Augustinus\"},\"users.age\":{\"value\":94.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":94.0},\"users"
      + ".average_age\":{\"value\":94.0}},{\"users.created_date\":{\"value\":15251},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1317720158000},"
      + "\"users.name\":{\"value\":\"Roming Raubenheimer\"},\"users.age\":{\"value\":92.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":92.0},\"users"
      + ".average_age\":{\"value\":92.0}},{\"users.created_date\":{\"value\":15243},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1317078357000},"
      + "\"users.name\":{\"value\":\"Slazac Sharanya\"},\"users.age\":{\"value\":83.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":83.0},\"users"
      + ".average_age\":{\"value\":83.0}},{\"users.created_date\":{\"value\":15238},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1316597408000},"
      + "\"users.name\":{\"value\":\"Hunziker Rassmann\"},\"users.age\":{\"value\":40.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":40.0},\"users"
      + ".average_age\":{\"value\":40.0}},{\"users.created_date\":{\"value\":15217},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1314793506000},"
      + "\"users.name\":{\"value\":\"Farissa Ivon\"},\"users.age\":{\"value\":73.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":73.0},\"users"
      + ".average_age\":{\"value\":73.0}},{\"users.created_date\":{\"value\":15212},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1314354877000},"
      + "\"users.name\":{\"value\":\"Richter Hodinski\"},\"users.age\":{\"value\":53.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":53.0},\"users"
      + ".average_age\":{\"value\":53.0}},{\"users.created_date\":{\"value\":15209},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1314096853000},"
      + "\"users.name\":{\"value\":\"Augustinus Ziegfried\"},\"users.age\":{\"value\":27.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":27.0},\"users"
      + ".average_age\":{\"value\":27.0}},{\"users.created_date\":{\"value\":15203},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1313584363000},"
      + "\"users.name\":{\"value\":\"Rocco Lincks\"},\"users.age\":{\"value\":93.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":93.0},\"users"
      + ".average_age\":{\"value\":93.0}},{\"users.created_date\":{\"value\":15195},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1312894310000},"
      + "\"users.name\":{\"value\":\"Brodner Guntermann\"},\"users.age\":{\"value\":56.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":56.0},\"users"
      + ".average_age\":{\"value\":56.0}},{\"users.created_date\":{\"value\":15191},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1312541289000},"
      + "\"users.name\":{\"value\":\"Mart Schwetlik\"},\"users.age\":{\"value\":31.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":31.0},\"users"
      + ".average_age\":{\"value\":31.0}},{\"users.created_date\":{\"value\":15190},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1312454576000},"
      + "\"users.name\":{\"value\":\"Neide Wirnseer\"},\"users.age\":{\"value\":71.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":71.0},\"users"
      + ".average_age\":{\"value\":71.0}},{\"users.created_date\":{\"value\":15190},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1312452217000},"
      + "\"users.name\":{\"value\":\"Herschal Hemsing\"},\"users.age\":{\"value\":27.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":27.0},\"users"
      + ".average_age\":{\"value\":27.0}},{\"users.created_date\":{\"value\":15188},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1312310975000},"
      + "\"users.name\":{\"value\":\"Faier Oona\"},\"users.age\":{\"value\":81.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":81.0},\"users"
      + ".average_age\":{\"value\":81.0}},{\"users.created_date\":{\"value\":15180},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1311584216000},"
      + "\"users.name\":{\"value\":\"Adolf Nikolai\"},\"users.age\":{\"value\":89.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":89.0},\"users"
      + ".average_age\":{\"value\":89.0}},{\"users.created_date\":{\"value\":15180},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1311582054000},"
      + "\"users.name\":{\"value\":\"Denhardt Alisha\"},\"users.age\":{\"value\":87.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":87.0},\"users"
      + ".average_age\":{\"value\":87.0}},{\"users.created_date\":{\"value\":15177},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1311338969000},"
      + "\"users.name\":{\"value\":\"Kusenberg Odette\"},\"users.age\":{\"value\":78.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":78.0},\"users"
      + ".average_age\":{\"value\":78.0}},{\"users.created_date\":{\"value\":15170},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1310721868000},"
      + "\"users.name\":{\"value\":\"Geoff Ziegfried\"},\"users.age\":{\"value\":83.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":83.0},\"users"
      + ".average_age\":{\"value\":83.0}},{\"users.created_date\":{\"value\":15167},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1310464594000},"
      + "\"users.name\":{\"value\":\"Raier Kloble\"},\"users.age\":{\"value\":62.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":62.0},\"users"
      + ".average_age\":{\"value\":62.0}},{\"users.created_date\":{\"value\":15166},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1310369694000},"
      + "\"users.name\":{\"value\":\"Schomi Ernst\"},\"users.age\":{\"value\":68.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":68.0},\"users"
      + ".average_age\":{\"value\":68.0}},{\"users.created_date\":{\"value\":15163},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1310122201000},"
      + "\"users.name\":{\"value\":\"Gais Tsoklan\"},\"users.age\":{\"value\":28.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":28.0},\"users"
      + ".average_age\":{\"value\":28.0}},{\"users.created_date\":{\"value\":15156},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1309513852000},"
      + "\"users.name\":{\"value\":\"Bilt Bartel\"},\"users.age\":{\"value\":67.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":67.0},\"users"
      + ".average_age\":{\"value\":67.0}},{\"users.created_date\":{\"value\":15153},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1309255834000},"
      + "\"users.name\":{\"value\":\"Pfenic Mangulabnan\"},\"users.age\":{\"value\":96.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":96.0},\"users"
      + ".average_age\":{\"value\":96.0}},{\"users.created_date\":{\"value\":15145},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1308568351000},"
      + "\"users.name\":{\"value\":\"Rassmann Warenius\"},\"users.age\":{\"value\":95.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":95.0},\"users"
      + ".average_age\":{\"value\":95.0}},{\"users.created_date\":{\"value\":15145},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1308568376000},"
      + "\"users.name\":{\"value\":\"Schipman Torge\"},\"users.age\":{\"value\":28.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":28.0},\"users"
      + ".average_age\":{\"value\":28.0}},{\"users.created_date\":{\"value\":15139},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1308045651000},"
      + "\"users.name\":{\"value\":\"Finarolli Doetschmann\"},\"users.age\":{\"value\":22.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":22.0},\"users"
      + ".average_age\":{\"value\":22.0}},{\"users.created_date\":{\"value\":15139},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1308041280000},"
      + "\"users.name\":{\"value\":\"Schorgmayer Swinner\"},\"users.age\":{\"value\":29.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":29.0},\"users"
      + ".average_age\":{\"value\":29.0}},{\"users.created_date\":{\"value\":15139},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1308043265000},"
      + "\"users.name\":{\"value\":\"Ziegfried Schwetlik\"},\"users.age\":{\"value\":88.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":88.0},\"users"
      + ".average_age\":{\"value\":88.0}},{\"users.created_date\":{\"value\":15121},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1306483063000},"
      + "\"users.name\":{\"value\":\"Bastian Orzesdek\"},\"users.age\":{\"value\":34.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":34.0},\"users"
      + ".average_age\":{\"value\":34.0}},{\"users.created_date\":{\"value\":15091},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1303892897000},"
      + "\"users.name\":{\"value\":\"Ulner Nixey\"},\"users.age\":{\"value\":39.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":39.0},\"users"
      + ".average_age\":{\"value\":39.0}},{\"users.created_date\":{\"value\":15089},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1303724778000},"
      + "\"users.name\":{\"value\":\"Ranthum Motsenbocker\"},\"users.age\":{\"value\":35.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":35.0},\"users"
      + ".average_age\":{\"value\":35.0}},{\"users.created_date\":{\"value\":15082},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1303121526000},"
      + "\"users.name\":{\"value\":\"Tarnoczi Oona\"},\"users.age\":{\"value\":60.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":60.0},\"users"
      + ".average_age\":{\"value\":60.0}},{\"users.created_date\":{\"value\":15070},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1302083363000},"
      + "\"users.name\":{\"value\":\"Goetti Kohlstruck\"},\"users.age\":{\"value\":73.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":73.0},\"users"
      + ".average_age\":{\"value\":73.0}},{\"users.created_date\":{\"value\":15065},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1301652628000},"
      + "\"users.name\":{\"value\":\"Litterst Manno\"},\"users.age\":{\"value\":91.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":91.0},\"users"
      + ".average_age\":{\"value\":91.0}},{\"users.created_date\":{\"value\":15053},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1300648324000},"
      + "\"users.name\":{\"value\":\"Majcei Cullop\"},\"users.age\":{\"value\":23.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":23.0},\"users"
      + ".average_age\":{\"value\":23.0}},{\"users.created_date\":{\"value\":15048},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1300193792000},"
      + "\"users.name\":{\"value\":\"Klein Reifschneider\"},\"users.age\":{\"value\":29.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":29.0},\"users"
      + ".average_age\":{\"value\":29.0}},{\"users.created_date\":{\"value\":15048},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1300200898000},"
      + "\"users.name\":{\"value\":\"Diana Briles\"},\"users.age\":{\"value\":77.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":77.0},\"users"
      + ".average_age\":{\"value\":77.0}},{\"users.created_date\":{\"value\":15008},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1296731354000},"
      + "\"users.name\":{\"value\":\"Jetzer Paschold\"},\"users.age\":{\"value\":82.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":82.0},\"users"
      + ".average_age\":{\"value\":82.0}},{\"users.created_date\":{\"value\":14975},\"users"
      + ".created_year\":{\"value\":2011},\"users.created_time\":{\"value\":1293842818000},"
      + "\"users.name\":{\"value\":\"Nikolai Lingenfelter\"},\"users.age\":{\"value\":69.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":69.0},\"users"
      + ".average_age\":{\"value\":69.0}},{\"users.created_date\":{\"value\":14945},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1291303917000},"
      + "\"users.name\":{\"value\":\"Derrick Hofer\"},\"users.age\":{\"value\":47.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":47.0},\"users"
      + ".average_age\":{\"value\":47.0}},{\"users.created_date\":{\"value\":14908},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1288061375000},"
      + "\"users.name\":{\"value\":\"Doela Warenius\"},\"users.age\":{\"value\":57.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":57.0},\"users"
      + ".average_age\":{\"value\":57.0}},{\"users.created_date\":{\"value\":14902},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1287601958000},"
      + "\"users.name\":{\"value\":\"Sacsu Wolf\"},\"users.age\":{\"value\":68.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":68.0},\"users"
      + ".average_age\":{\"value\":68.0}},{\"users.created_date\":{\"value\":14894},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1286924692000},"
      + "\"users.name\":{\"value\":\"Kelting Oshanny\"},\"users.age\":{\"value\":35.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":35.0},\"users"
      + ".average_age\":{\"value\":35.0}},{\"users.created_date\":{\"value\":14893},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1286788336000},"
      + "\"users.name\":{\"value\":\"Kraemer Franc\"},\"users.age\":{\"value\":87.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":87.0},\"users"
      + ".average_age\":{\"value\":87.0}},{\"users.created_date\":{\"value\":14889},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1286439797000},"
      + "\"users.name\":{\"value\":\"Metz Riegerix\"},\"users.age\":{\"value\":58.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":58.0},\"users"
      + ".average_age\":{\"value\":58.0}},{\"users.created_date\":{\"value\":14889},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1286471274000},"
      + "\"users.name\":{\"value\":\"Warnk Pelger\"},\"users.age\":{\"value\":49.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":49.0},\"users"
      + ".average_age\":{\"value\":49.0}},{\"users.created_date\":{\"value\":14874},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1285148625000},"
      + "\"users.name\":{\"value\":\"Maurer Sieber\"},\"users.age\":{\"value\":67.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":67.0},\"users"
      + ".average_age\":{\"value\":67.0}},{\"users.created_date\":{\"value\":14868},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1284629978000},"
      + "\"users.name\":{\"value\":\"Sharanya Irma\"},\"users.age\":{\"value\":31.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":31.0},\"users"
      + ".average_age\":{\"value\":31.0}},{\"users.created_date\":{\"value\":14860},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283935508000},"
      + "\"users.name\":{\"value\":\"Ferderber Lingenfelter\"},\"users.age\":{\"value\":22.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":22.0},\"users"
      + ".average_age\":{\"value\":22.0}},{\"users.created_date\":{\"value\":14859},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283853687000},"
      + "\"users.name\":{\"value\":\"Gaensli Magdalene\"},\"users.age\":{\"value\":22.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":22.0},\"users"
      + ".average_age\":{\"value\":22.0}},{\"users.created_date\":{\"value\":14858},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283816749000},"
      + "\"users.name\":{\"value\":\"Justinovia Oresnik\"},\"users.age\":{\"value\":25.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":25.0},\"users"
      + ".average_age\":{\"value\":25.0}},{\"users.created_date\":{\"value\":14854},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283419292000},"
      + "\"users.name\":{\"value\":\"Unta Atoulf\"},\"users.age\":{\"value\":48.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":48.0},\"users"
      + ".average_age\":{\"value\":48.0}},{\"users.created_date\":{\"value\":14853},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283330361000},"
      + "\"users.name\":{\"value\":\"Floidea Juric\"},\"users.age\":{\"value\":18.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":18.0},\"users"
      + ".average_age\":{\"value\":18.0}},{\"users.created_date\":{\"value\":14851},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1283157151000},"
      + "\"users.name\":{\"value\":\"Yuo-jie Schmalisch\"},\"users.age\":{\"value\":51.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":51.0},\"users"
      + ".average_age\":{\"value\":51.0}},{\"users.created_date\":{\"value\":14847},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282816345000},"
      + "\"users.name\":{\"value\":\"Boholt Staut\"},\"users.age\":{\"value\":56.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":56.0},\"users"
      + ".average_age\":{\"value\":56.0}},{\"users.created_date\":{\"value\":14847},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282812014000},"
      + "\"users.name\":{\"value\":\"Slazac Wertschnig\"},\"users.age\":{\"value\":89.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":89.0},\"users"
      + ".average_age\":{\"value\":89.0}},{\"users.created_date\":{\"value\":14847},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282816833000},"
      + "\"users.name\":{\"value\":\"Ferencik Roland\"},\"users.age\":{\"value\":42.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":42.0},\"users"
      + ".average_age\":{\"value\":42.0}},{\"users.created_date\":{\"value\":14846},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282727309000},"
      + "\"users.name\":{\"value\":\"Maximilian Brechtelsbauer\"},\"users.age\":{\"value\":59.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":59.0},\"users"
      + ".average_age\":{\"value\":59.0}},{\"users.created_date\":{\"value\":14846},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282729314000},"
      + "\"users.name\":{\"value\":\"Robel Niehaus\"},\"users.age\":{\"value\":32.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":32.0},\"users"
      + ".average_age\":{\"value\":32.0}},{\"users.created_date\":{\"value\":14846},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282725622000},"
      + "\"users.name\":{\"value\":\"Hartmut Schoppenhorst\"},\"users.age\":{\"value\":72.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":72.0},\"users"
      + ".average_age\":{\"value\":72.0}},{\"users.created_date\":{\"value\":14845},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282638341000},"
      + "\"users.name\":{\"value\":\"Sicoe Dietel\"},\"users.age\":{\"value\":61.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":61.0},\"users"
      + ".average_age\":{\"value\":61.0}},{\"users.created_date\":{\"value\":14845},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282643205000},"
      + "\"users.name\":{\"value\":\"Chernbach Kaddoura\"},\"users.age\":{\"value\":45.0},\"users"
      + ".is45or30\":{\"value\":true},\"EXPR__6\":{\"value\":45.0},\"users"
      + ".average_age\":{\"value\":45.0}},{\"users.created_date\":{\"value\":14845},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282638263000},"
      + "\"users.name\":{\"value\":\"Faier Wendt\"},\"users.age\":{\"value\":76.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":76.0},\"users"
      + ".average_age\":{\"value\":76.0}},{\"users.created_date\":{\"value\":14845},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282639897000},"
      + "\"users.name\":{\"value\":\"Oresnek Schaller\"},\"users.age\":{\"value\":30.0},\"users"
      + ".is45or30\":{\"value\":true},\"EXPR__6\":{\"value\":30.0},\"users"
      + ".average_age\":{\"value\":30.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282557023000},"
      + "\"users.name\":{\"value\":\"Gaensli Niehaus\"},\"users.age\":{\"value\":40.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":40.0},\"users"
      + ".average_age\":{\"value\":40.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282560871000},"
      + "\"users.name\":{\"value\":\"Meurer Neininger\"},\"users.age\":{\"value\":78.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":78.0},\"users"
      + ".average_age\":{\"value\":78.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282557593000},"
      + "\"users.name\":{\"value\":\"Martell Bernard\"},\"users.age\":{\"value\":62.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":62.0},\"users"
      + ".average_age\":{\"value\":62.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282557121000},"
      + "\"users.name\":{\"value\":\"Iurist Warnk\"},\"users.age\":{\"value\":75.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":75.0},\"users"
      + ".average_age\":{\"value\":75.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282567572000},"
      + "\"users.name\":{\"value\":\"Frey Reifschneider\"},\"users.age\":{\"value\":67.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":67.0},\"users"
      + ".average_age\":{\"value\":67.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282555404000},"
      + "\"users.name\":{\"value\":\"Raphael Shaprisha\"},\"users.age\":{\"value\":19.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":19.0},\"users"
      + ".average_age\":{\"value\":19.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282556522000},"
      + "\"users.name\":{\"value\":\"Hektor Doela\"},\"users.age\":{\"value\":57.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":57.0},\"users"
      + ".average_age\":{\"value\":57.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282557474000},"
      + "\"users.name\":{\"value\":\"Pelger Kroll\"},\"users.age\":{\"value\":37.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":37.0},\"users"
      + ".average_age\":{\"value\":37.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282560000000},"
      + "\"users.name\":{\"value\":\"Lambert Wertschnig\"},\"users.age\":{\"value\":90.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":90.0},\"users"
      + ".average_age\":{\"value\":90.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282559280000},"
      + "\"users.name\":{\"value\":\"Muzzleman Ruppert\"},\"users.age\":{\"value\":78.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":78.0},\"users"
      + ".average_age\":{\"value\":78.0}},{\"users.created_date\":{\"value\":14844},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1282560244000},"
      + "\"users.name\":{\"value\":\"Gumpla Nixey\"},\"users.age\":{\"value\":18.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":18.0},\"users"
      + ".average_age\":{\"value\":18.0}},{\"users.created_date\":{\"value\":14837},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281952766000},"
      + "\"users.name\":{\"value\":\"Augustinus Mathilda\"},\"users.age\":{\"value\":51.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":51.0},\"users"
      + ".average_age\":{\"value\":51.0}},{\"users.created_date\":{\"value\":14834},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281686134000},"
      + "\"users.name\":{\"value\":\"Musbah Fernando\"},\"users.age\":{\"value\":26.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":26.0},\"users"
      + ".average_age\":{\"value\":26.0}},{\"users.created_date\":{\"value\":14834},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281685698000},"
      + "\"users.name\":{\"value\":\"Ager Mathilda\"},\"users.age\":{\"value\":70.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":70.0},\"users"
      + ".average_age\":{\"value\":70.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281632163000},"
      + "\"users.name\":{\"value\":\"Gais Lohkamp\"},\"users.age\":{\"value\":30.0},\"users"
      + ".is45or30\":{\"value\":true},\"EXPR__6\":{\"value\":30.0},\"users"
      + ".average_age\":{\"value\":30.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281635580000},"
      + "\"users.name\":{\"value\":\"Rautu Kroll\"},\"users.age\":{\"value\":70.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":70.0},\"users"
      + ".average_age\":{\"value\":70.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281632646000},"
      + "\"users.name\":{\"value\":\"Naiux Torge\"},\"users.age\":{\"value\":84.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":84.0},\"users"
      + ".average_age\":{\"value\":84.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281632943000},"
      + "\"users.name\":{\"value\":\"Bors Lohkamp\"},\"users.age\":{\"value\":77.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":77.0},\"users"
      + ".average_age\":{\"value\":77.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281631587000},"
      + "\"users.name\":{\"value\":\"Benzmiller Reifschneider\"},\"users.age\":{\"value\":24.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":24.0},\"users"
      + ".average_age\":{\"value\":24.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281637134000},"
      + "\"users.name\":{\"value\":\"Schwaller Ferderber\"},\"users.age\":{\"value\":62.0},"
      + "\"users.is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":62.0},\"users"
      + ".average_age\":{\"value\":62.0}},{\"users.created_date\":{\"value\":14833},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281631812000},"
      + "\"users.name\":{\"value\":\"Voigt Isoldas\"},\"users.age\":{\"value\":22.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":22.0},\"users"
      + ".average_age\":{\"value\":22.0}},{\"users.created_date\":{\"value\":14832},\"users"
      + ".created_year\":{\"value\":2010},\"users.created_time\":{\"value\":1281545389000},"
      + "\"users.name\":{\"value\":\"Obeldobel Kyler\"},\"users.age\":{\"value\":56.0},\"users"
      + ".is45or30\":{\"value\":false},\"EXPR__6\":{\"value\":56.0},\"users"
      + ".average_age\":{\"value\":56.0}}]}";

  /**
   * This is a real signature from Looker for the following query in `json_bi` format, specifically
   * pry'd from jdbc_server_test_helpers.
   *
   * SELECT `users.created_year` , AGGREGATE(`users.names`) as `names` , AGGREGATE(`users.ages`) as
   * `ages` FROM `example`.`users` GROUP BY `users.created_year` LIMIT 2
   */
  public static String stubbedListMeasuresSignature = "{\"columns\":[{\"ordinal\":0,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":10,\"label\":\"users.created_year\","
      + "\"columnName\":\"users.created_year\",\"schemaName\":\"example\",\"precision\":10,"
      + "\"scale\":0,\"tableName\":\"users\",\"catalogName\":null,\"type\":{\"type\":\"scalar\","
      + "\"id\":4,\"name\":\"INTEGER\",\"rep\":\"INTEGER\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.lang.Integer\"},{\"ordinal\":1,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":1,\"signed\":true,\"displaySize\":-1,\"label\":\"names\","
      + "\"columnName\":\"names\",\"schemaName\":null,\"precision\":0,\"scale\":0,"
      + "\"tableName\":null,\"catalogName\":null,\"type\":{\"type\":\"array\",\"name\":\"VARCHAR "
      + "ARRAY\",\"rep\":\"STRING\",\"component\":{\"type\":\"scalar\",\"id\":12,"
      + "\"name\":\"VARCHAR\",\"rep\":\"STRING\"},\"id\":2003},\"readOnly\":true,"
      + "\"writable\":false,\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Array\"},"
      + "{\"ordinal\":2,\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,"
      + "\"currency\":false,\"nullable\":1,\"signed\":true,\"displaySize\":-1,\"label\":\"ages\","
      + "\"columnName\":\"ages\",\"schemaName\":null,\"precision\":0,\"scale\":0,"
      + "\"tableName\":null,\"catalogName\":null,\"type\":{\"type\":\"array\",\"name\":\"VARCHAR "
      + "ARRAY\",\"rep\":\"STRING\",\"component\":{\"type\":\"scalar\",\"id\":12,"
      + "\"name\":\"VARCHAR\",\"rep\":\"STRING\"},\"id\":2003},\"readOnly\":true,"
      + "\"writable\":false,\"definitelyWritable\":false,\"columnClassName\":\"java.sql"
      + ".Array\"}],\"sql\":\"SELECT `users.created_year`\\n , AGGREGATE(`users.names`) as "
      + "`names`\\n , AGGREGATE(`users.ages`) as `ages`\\nFROM `example`.`users`\\nGROUP BY "
      + "`users.created_year`\\nLIMIT 2\\n\",\"parameters\":[],"
      + "\"cursorFactory\":{\"style\":\"ARRAY\",\"clazz\":null,\"fieldNames\":null},"
      + "\"statementType\":\"SELECT\"}";

  public static String stubbedListMeasureResponse = "{\"metadata\":{\"big_query_metadata"
      + "\":{\"total_bytes_processed\":2819,\"backend_cache_hit\":false},"
      + "\"fields\":{\"dimensions\":[{\"sql\":\"{% if _dialect._name contains 'druid' %} "
      + "TIME_PARSE(${TABLE}.created_at, 'yyyy-MM-dd HH:mm:ss') {% else %} ${TABLE}.created_at {%"
      + " endif %}\\n      \",\"view\":\"users\",\"dimension_group\":\"users.created\","
      + "\"category\":\"dimension\",\"field_group_label\":\"Created Date\",\"name\":\"users"
      + ".created_year\",\"type\":\"date_year\",\"view_label\":\"Users\",\"label\":\"Users "
      + "Created Year\",\"field_group_variant\":\"Year\",\"hidden\":false,\"description\":null}],"
      + "\"measures\":[{\"sql\":\"${name::string}\",\"view\":\"users\",\"dimension_group\":null,"
      + "\"category\":\"measure\",\"field_group_label\":null,\"name\":\"users.names\","
      + "\"type\":\"list\",\"view_label\":\"Users\",\"label\":\"Users Names\","
      + "\"field_group_variant\":\"Names\",\"hidden\":false,\"description\":null},"
      + "{\"sql\":\"${age::string}\",\"view\":\"users\",\"dimension_group\":null,"
      + "\"category\":\"measure\",\"field_group_label\":null,\"name\":\"users.ages\","
      + "\"type\":\"list\",\"view_label\":\"Users\",\"label\":\"Users Ages\","
      + "\"field_group_variant\":\"Ages\",\"hidden\":false,\"description\":null}],\"pivots\":[]},"
      + "\"pivots\":[],\"filters\":{},\"filter_expression\":null,\"columns_truncated\":false,"
      + "\"has_totals\":false,\"has_subtotals\":false,\"sql\":\"SELECT\\n    (EXTRACT(YEAR FROM "
      + "created_at)) AS users_created_year,\\n    STRING_AGG(DISTINCT CAST(users.name AS STRING)"
      + ", '|RECORD|') AS users_names,\\n    STRING_AGG(DISTINCT CAST((CAST(users.age AS STRING))"
      + " AS STRING), '|RECORD|') AS users_ages\\nFROM\\n    users AS users\\nGROUP BY\\n    "
      + "1\\nORDER BY\\n    1 DESC\\nLIMIT 2\"},\"rows\":[{\"users"
      + ".created_year\":{\"value\":2011},\"users.names\":{\"value\":[\"Nikolai Lingenfelter\","
      + "\"Ziegfried Schwetlik\",\"Schorgmayer Swinner\",\"Finarolli Doetschmann\",\"Schipman "
      + "Torge\",\"Rassmann Warenius\",\"Pfenic Mangulabnan\",\"Litterst Manno\",\"Goetti "
      + "Kohlstruck\",\"Hunziker Rassmann\",\"Slazac Sharanya\",\"Tarnoczi Oona\",\"Ranthum "
      + "Motsenbocker\",\"Ulner Nixey\",\"Reinoehl Augustinus\",\"Bilt Bartel\",\"Gais Tsoklan\","
      + "\"Schomi Ernst\",\"Raier Kloble\",\"Jetzer Paschold\",\"Geoff Ziegfried\",\"Kusenberg "
      + "Odette\",\"Denhardt Alisha\",\"Adolf Nikolai\",\"Roming Raubenheimer\",\"Bastian "
      + "Orzesdek\",\"Faier Oona\",\"Neide Wirnseer\",\"Herschal Hemsing\",\"Mart Schwetlik\","
      + "\"Brodner Guntermann\",\"Rocco Lincks\",\"Augustinus Ziegfried\",\"Richter Hodinski\","
      + "\"Diana Briles\",\"Klein Reifschneider\",\"Farissa Ivon\",\"Majcei Cullop\"]},\"users"
      + ".ages\":{\"value\":[\"69\",\"88\",\"29\",\"22\",\"28\",\"95\",\"96\",\"91\",\"73\","
      + "\"40\",\"83\",\"60\",\"35\",\"39\",\"94\",\"67\",\"68\",\"62\",\"82\",\"78\",\"87\","
      + "\"89\",\"92\",\"34\",\"81\",\"71\",\"27\",\"31\",\"56\",\"93\",\"53\",\"77\",\"23\"]}},"
      + "{\"users.created_year\":{\"value\":2010},\"users.names\":{\"value\":[\"Floidea Juric\","
      + "\"Unta Atoulf\",\"Justinovia Oresnik\",\"Gaensli Magdalene\",\"Ferderber Lingenfelter\","
      + "\"Sharanya Irma\",\"Maurer Sieber\",\"Derrick Hofer\",\"Warnk Pelger\",\"Metz "
      + "Riegerix\",\"Kraemer Franc\",\"Kelting Oshanny\",\"Sacsu Wolf\",\"Doela Warenius\","
      + "\"Obeldobel Kyler\",\"Schwaller Ferderber\",\"Voigt Isoldas\",\"Benzmiller "
      + "Reifschneider\",\"Bors Lohkamp\",\"Naiux Torge\",\"Rautu Kroll\",\"Gais Lohkamp\",\"Ager"
      + " Mathilda\",\"Musbah Fernando\",\"Augustinus Mathilda\",\"Gumpla Nixey\",\"Muzzleman "
      + "Ruppert\",\"Lambert Wertschnig\",\"Pelger Kroll\",\"Hektor Doela\",\"Raphael "
      + "Shaprisha\",\"Gaensli Niehaus\",\"Frey Reifschneider\",\"Iurist Warnk\",\"Meurer "
      + "Neininger\",\"Martell Bernard\",\"Sicoe Dietel\",\"Oresnek Schaller\",\"Chernbach "
      + "Kaddoura\",\"Faier Wendt\",\"Hartmut Schoppenhorst\",\"Robel Niehaus\",\"Maximilian "
      + "Brechtelsbauer\",\"Ferencik Roland\",\"Slazac Wertschnig\",\"Boholt Staut\",\"Yuo-jie "
      + "Schmalisch\"]},\"users.ages\":{\"value\":[\"18\",\"48\",\"25\",\"22\",\"31\",\"67\","
      + "\"47\",\"49\",\"58\",\"87\",\"35\",\"68\",\"57\",\"56\",\"62\",\"24\",\"77\",\"84\","
      + "\"70\",\"30\",\"26\",\"51\",\"78\",\"90\",\"37\",\"19\",\"40\",\"75\",\"61\",\"45\","
      + "\"76\",\"72\",\"32\",\"59\",\"42\",\"89\"]}}]}";
  public static String stubbedArrayPrimitivesSig = "{\"columns\":[{\"ordinal\":0,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":0,\"signed\":true,\"displaySize\":14,\"label\":\"test_name\","
      + "\"columnName\":\"test_name\",\"schemaName\":null,\"precision\":14,\"scale\":0,"
      + "\"tableName\":null,\"catalogName\":null,\"type\":{\"type\":\"scalar\",\"id\":1,"
      + "\"name\":\"CHAR\",\"rep\":\"STRING\"},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.lang.String\"},{\"ordinal\":1,"
      + "\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,\"currency\":false,"
      + "\"nullable\":0,\"signed\":true,\"displaySize\":-1,\"label\":\"int_arrs\","
      + "\"columnName\":\"int_arrs\",\"schemaName\":null,\"precision\":0,\"scale\":0,"
      + "\"tableName\":null,\"catalogName\":null,\"type\":{\"type\":\"array\",\"name\":\"INTEGER "
      + "ARRAY\",\"rep\":\"PRIMITIVE_INT\",\"component\":{\"type\":\"scalar\",\"id\":4,"
      + "\"name\":\"INTEGER\",\"rep\":\"PRIMITIVE_INT\"},\"id\":2003},\"readOnly\":true,"
      + "\"writable\":false,\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Array\"},"
      + "{\"ordinal\":2,\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,"
      + "\"currency\":false,\"nullable\":0,\"signed\":true,\"displaySize\":-1,"
      + "\"label\":\"float_arr\",\"columnName\":\"float_arr\",\"schemaName\":null,"
      + "\"precision\":0,\"scale\":0,\"tableName\":null,\"catalogName\":null,"
      + "\"type\":{\"type\":\"array\",\"name\":\"DECIMAL(2, 1) ARRAY\",\"rep\":\"NUMBER\","
      + "\"component\":{\"type\":\"scalar\",\"id\":3,\"name\":\"DECIMAL\",\"rep\":\"NUMBER\"},"
      + "\"id\":2003},\"readOnly\":true,\"writable\":false,\"definitelyWritable\":false,"
      + "\"columnClassName\":\"java.sql.Array\"},{\"ordinal\":3,\"autoIncrement\":false,"
      + "\"caseSensitive\":true,\"searchable\":false,\"currency\":false,\"nullable\":0,"
      + "\"signed\":true,\"displaySize\":-1,\"label\":\"varchar_arr\","
      + "\"columnName\":\"varchar_arr\",\"schemaName\":null,\"precision\":0,\"scale\":0,"
      + "\"tableName\":null,\"catalogName\":null,\"type\":{\"type\":\"array\",\"name\":\"VARCHAR"
      + "(4) ARRAY\",\"rep\":\"STRING\",\"component\":{\"type\":\"scalar\",\"id\":12,"
      + "\"name\":\"VARCHAR\",\"rep\":\"STRING\"},\"id\":2003},\"readOnly\":true,"
      + "\"writable\":false,\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Array\"},"
      + "{\"ordinal\":4,\"autoIncrement\":false,\"caseSensitive\":true,\"searchable\":false,"
      + "\"currency\":false,\"nullable\":0,\"signed\":true,\"displaySize\":-1,"
      + "\"label\":\"boolean_arr\",\"columnName\":\"boolean_arr\",\"schemaName\":null,"
      + "\"precision\":0,\"scale\":0,\"tableName\":null,\"catalogName\":null,"
      + "\"type\":{\"type\":\"array\",\"name\":\"BOOLEAN ARRAY\",\"rep\":\"PRIMITIVE_BOOLEAN\","
      + "\"component\":{\"type\":\"scalar\",\"id\":16,\"name\":\"BOOLEAN\","
      + "\"rep\":\"PRIMITIVE_BOOLEAN\"},\"id\":2003},\"readOnly\":true,\"writable\":false,"
      + "\"definitelyWritable\":false,\"columnClassName\":\"java.sql.Array\"}],\"sql\":\"SELECT "
      + "\\\"testing arrays\\\" as `test_name`\\n , array[1, 2, 3] as `int_arrs`\\n , array[1.1, "
      + "2.2, 3.3] as `float_arr`\\n , array[\\\"this\\\", \\\"and\\\", \\\"that\\\"] as "
      + "`varchar_arr`\\n , array[true, false, false] as `boolean_arr`\\nFROM `example`"
      + ".`users`\\nLIMIT 1\\n\",\"parameters\":[],\"cursorFactory\":{\"style\":\"ARRAY\","
      + "\"clazz\":null,\"fieldNames\":null},\"statementType\":\"SELECT\"}";
  public static String stubbedArrayPrimitivesResponse = "{\"metadata\":{\"big_query_metadata"
      + "\":{\"total_bytes_processed\":0,\"backend_cache_hit\":false},"
      + "\"fields\":{\"dimensions\":[{\"sql\":null,\"view\":\"users\",\"dimension_group\":null,"
      + "\"category\":\"dimension\",\"field_group_label\":null,\"name\":\"test_name\","
      + "\"type\":\"string\",\"view_label\":null,\"label\":\"test_name\","
      + "\"field_group_variant\":\"test_name\",\"hidden\":false,\"description\":null},"
      + "{\"sql\":null,\"view\":\"users\",\"dimension_group\":null,\"category\":\"dimension\","
      + "\"field_group_label\":null,\"name\":\"int_arrs\",\"type\":\"list\",\"view_label\":null,"
      + "\"label\":\"int_arrs\",\"field_group_variant\":\"int_arrs\",\"hidden\":false,"
      + "\"description\":null},{\"sql\":null,\"view\":\"users\",\"dimension_group\":null,"
      + "\"category\":\"dimension\",\"field_group_label\":null,\"name\":\"float_arr\","
      + "\"type\":\"list\",\"view_label\":null,\"label\":\"float_arr\","
      + "\"field_group_variant\":\"float_arr\",\"hidden\":false,\"description\":null},"
      + "{\"sql\":null,\"view\":\"users\",\"dimension_group\":null,\"category\":\"dimension\","
      + "\"field_group_label\":null,\"name\":\"varchar_arr\",\"type\":\"list\","
      + "\"view_label\":null,\"label\":\"varchar_arr\",\"field_group_variant\":\"varchar_arr\","
      + "\"hidden\":false,\"description\":null},{\"sql\":null,\"view\":\"users\","
      + "\"dimension_group\":null,\"category\":\"dimension\",\"field_group_label\":null,"
      + "\"name\":\"boolean_arr\",\"type\":\"list\",\"view_label\":null,"
      + "\"label\":\"boolean_arr\",\"field_group_variant\":\"boolean_arr\",\"hidden\":false,"
      + "\"description\":null}],\"measures\":[],\"pivots\":[]},\"pivots\":[],\"filters\":{},"
      + "\"filter_expression\":null,\"columns_truncated\":false,\"has_totals\":false,"
      + "\"has_subtotals\":false,\"sql\":\"SELECT\\n    'testing arrays' AS test_name,\\n    "
      + "ARRAY[1, 2, 3] AS int_arrs,\\n    ARRAY[1.1, 2.2, 3.3] AS float_arr,\\n    ARRAY['this',"
      + " 'and', 'that'] AS varchar_arr,\\n    ARRAY[TRUE, FALSE, FALSE] AS boolean_arr\\nFROM\\n"
      + "    users AS users\\nORDER BY\\n    1\\nLIMIT 1\"},"
      + "\"rows\":[{\"test_name\":{\"value\":\"testing arrays\"},\"int_arrs\":{\"value\":[\"1\","
      + "\"2\",\"3\"]},\"float_arr\":{\"value\":[\"1.1\",\"2.2\",\"3.3\"]},"
      + "\"varchar_arr\":{\"value\":[\"this\",\"and\",null,\"that\"]},"
      + "\"boolean_arr\":{\"value\":[\"true\",\"false\",\"false\"]}}]}";
}
